apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: demo 
  namespace: demo-environment
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels: 
      app: demo
  template:
    metadata:
      labels:
        app: demo 
    spec:
      containers:
      - name: demo 
        image: {{ .Values.app.image.name }}:{{ .Values.app.image.tag }}
        ports:
        - containerPort: {{ .Values.app.containerPort }}