apiVersion: v1
kind: Service
metadata:
  name: demo
  namespace: {{ .Values.namespace }}
  labels:
    app: demo
spec:
  selector:
    app: demo
  type: LoadBalancer
  ports:
    - port: {{ .Values.app.clusterPort }}
      protocol: TCP
      targetPort: {{ .Values.app.containerPort }}
